exclude: "^candidate/tests/|/migrations/"
default_stages: [commit]

repos:
  # Core pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]
      - id: check-merge-conflict
        types: [python]
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
        types: [python]
      - id: check-json
      - id: check-toml
      - id: debug-statements
        types: [python]
      - id: detect-private-key
      - id: check-ast
        types: [python]
      - id: check-builtin-literals
        types: [python]
      - id: check-symlinks

  # Python code formatting and quality
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
        types: [python]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [--line-length=120]
        types: [python]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120"]
        types: [python]

  - repo: https://github.com/myint/autoflake
    rev: v2.3.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
        types: [python]

  # Code quality and linting
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --max-complexity=12
          - --extend-ignore=E203,W503,E501
          - --per-file-ignores=__init__.py:F401
        types: [python]

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.7'
    hooks:
      - id: bandit
        args: [--skip, "B101,B601", --recursive, --exclude, "tests/"]
        exclude: "tests/"
        types: [python]

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: [--ignore-missing-imports, --no-strict-optional]
        exclude: "tests/"
        types: [python]

  # Local hooks for project-specific checks
  - repo: local
    hooks:
      - id: run-tests
        name: run tests
        language: system
        entry: docker-compose -f ./compose/docker-compose.test.yml run --rm -T test
        pass_filenames: false
        always_run: true
        types: [python]

      - id: django-check
        name: django check
        language: system
        entry: docker-compose -f ./compose/docker-compose.yml run --rm -T api python manage.py check
        pass_filenames: false
        always_run: true
        types: [python]