# Generated by Django 5.2.4 on 2025-07-12 12:27

import candidate.models
import core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True, validators=[core.validators.PhoneNumberValidator()])),
                ('date_of_birth', models.DateField(validators=[core.validators.AgeValidator(max_age=100, min_age=16)])),
                ('years_of_experience', models.PositiveIntegerField(validators=[core.validators.ExperienceValidator(max_years=50, min_years=0)])),
                ('department', models.CharField(choices=[('it', 'Information Technology'), ('hr', 'Human Resources'), ('finance', 'Finance')], db_index=True, max_length=10)),
                ('resume', models.FileField(max_length=500, upload_to=candidate.models.candidate_resume_path, validators=[core.validators.FileSizeValidator(max_size_mb=5), core.validators.FileTypeValidator()])),
                ('current_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], db_index=True, default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department', 'created_at'], name='candidates_departm_8feeb5_idx'), models.Index(fields=['current_status', 'created_at'], name='candidates_current_bc1381_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('admin_name', models.CharField(default='System Admin', max_length=255)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='candidate.candidate')),
            ],
            options={
                'db_table': 'status_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate', 'created_at'], name='status_hist_candida_47fe2d_idx')],
            },
        ),
    ]
